#-- generate full metadata for hdb3d-data

import json
import uuid
import os
from datetime import date

def main():
    with open('_data/hdbTest.json', 'r+') as cm:
        json_cm = json.load(cm)
        json_cm['metadata'] = generate_metadata(json_cm, cm)
        cm.seek(0)
        cm.write(json.dumps(json_cm, indent=2))
        cm.truncate()   
    print("Full metadata written to file")

def generate_metadata(citymodel,cm_name):
    metadata = {
        "citymodelIdentifier": str(uuid.uuid4()),
        "datasetTitle": "3D city model of public housing (HDB) buildings in Singapore",
        "datasetReferenceDate": str(date.today()),
        "geographicLocation": "Singapore, Republic of Singapore",
        "datasetLanguage": "English",
        "datasetCharacterSet": "UTF-8",
        "datasetTopicCategory": "geoscientificInformation",
        "distributionFormatVersion": citymodel["version"],
        "referenceSystem": "urn:ogc:def:crs:EPSG::3414",
        "spatialRepresentationType": "vector",
        "onlineResource": "https://github.com/ualsg/hdb3d-data",
        "fileIdentifier": os.path.basename(cm_name.name),
        "geographicalExtent": [
            11474.615816611371,
            28054.808157231186,
            0,
            45326.44585339671,
            48758.78176700817,
            141.3
        ],
        "datasetPointOfContact": {
            "contactName": "NUS Urban Analytics Lab, National University of Singapore",
            "emailAddress": "filip@nus.edu.sg",
            "contactType": "organization",
            "website": "https://ual.sg/"
            },
        "metadataStandard": "ISO 19115 - Geographic Information - Metadata",
        "metadataStandardVersion": "ISO 19115:2014(E)",
        "metadataLanguage": "English",
        "metadataCharacterSet": "UTF-8",
        "metadataDateStamp": str(date.today()),
        "metadataPointOfContact":{
            "contactName": "Anna Labetski",
            "emailAddress": "a.labetski@tudelft.nl",
            "contactType": "processor",
            "website": "https://3d.bk.tudelft.nl/alabetski/"
            },
        "lineage":[
            {
                "thematicModels":["Building"],
                "source":[{
                    "description": "2D building footprints from OpenStreetMap",
                    "sourceCitation": "https://www.openstreetmap.org/#map=12/1.3649/103.8229",
                    "SourceReferenceSystem": "urn:ogc:def:crs:EPSG::4326"
                    },
                    {
                    "description": "HDB Property Information",
                    "sourceCitation": "https://data.gov.sg/dataset/hdb-property-information",
                    }
                ],
                "processStep":{
                    "description": "Buildings extruded to LoD1.2 based on number of stories.",
                    "processor":{
                        "contactName": "NUS Urban Analytics Lab, National University of Singapore",
                        "emailAddress": "filip@nus.edu.sg",
                        "contactType": "organization",
                        "website": "https://ual.sg/"
                        },
                    "stepDateTime": str(date.today()),
                    "reference": "https://github.com/ualsg/hdb3d-code"
                }
            }],
        "temporalExtent":{
            "startDate": "2019-07-05",
            "endDate": "2019-07-18",
        },
        "abstract": "A 3D city model of all public housing (HDB) buildings in Singapore, generated by conflating different open datasets. Public housing accommodates the predominant majority of Singapore’s population, so the dataset covers most of the nation’s residential buildings. Generated using extrusion, with the number of storeys of each block utilised as a proxy for the height. Cities around the world are increasingly releasing their 3D city models as open data. Researchers and practitioners in different disciplines are using 3D geoinformation to carry out a variety of spatial analyses. This model is openly available, hopefully benefiting researchers who previously did not have access to such data.",
        "specificUsage": "Openly available 3D city model of Singapore",
        "keywords":[
            "cityJSON",
            "3D",
            "city model",
            "public housing",
            "Singapore",
            "buildings"
        ],
        "constraints":{
            "legalConstraints":"licenceUnrestricted",
            "securityConstraints":"unclassified",
            "userNote":"open access"
        },
        "thematicModels":[
            "Building"
        ],
        "textures": "absent",
        "materials": "absent",
        "presentLoDs":{
            "1.2": len(citymodel["CityObjects"])
        },
        "cityfeatureMetadata":{
            #Right now only Building but can add other modules in the future
            "Building":{
                "uniqueFeatureCount": len(citymodel["CityObjects"]),
                "aggregateFeatureCount": len(citymodel["CityObjects"]),
                "presentLoDs":{
                    "1.2": len(citymodel["CityObjects"])
                }
                #TO DO: BuildingParts and BuildingInstallations
            }
        }
    }
    return metadata

if __name__ == '__main__':
    main()